######################################################################
# Automatically generated by qmake (3.0) ?? ??? 4 14:29:48 2017
######################################################################

TEMPLATE = lib
TARGET = ftplibpp
INCLUDEPATH += $$PWD\..\openssl\include

# Input
HEADERS += ftplib.h
SOURCES += ftplib.cpp
DEFINES += NOLFS NOSSL
