######################################################################
# Automatically generated by qmake (3.0) ?? ??? 4 14:29:48 2017
######################################################################

TEMPLATE = lib
TARGET = ftplibpp
INCLUDEPATH += .
LIBS += -L$$PWD/lib -lssl -lcrypto
win32: LIBS += -lws2_32

# Input
HEADERS += ftplib.h
SOURCES += ftplib.cpp
DEFINES += NOLFS
